name: ra-functions-ci-workflow

on: 
  workflow_call:
    inputs:
      node_version:
        type: string
        description: 'Node version to use'     
        required: true
        default: '18.x'

jobs:
  continuos-integration-job:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Source Code'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node ${{ inputs.node_version }} Environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}

    - name: 'npm install'
      shell: bash
      run: |
        npm install

    - name: 'npm build'
      shell: bash 
      run: |
        echo 'npm run build:prod'
    
    - name: 'npm test'
      shell: bash 
      working-directory: ${{ inputs.working_directory }}
      run: |
        echo 'npm run test:coverage'

    - name: Zip artifact for deployment
      working-directory: ${{ inputs.working_directory }}
      run: zip -r ${{ needs.ra_version.outputs.release }}.zip * -x 'node_modules/*'
      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: ArtifactName
        path: ${{ inputs.working_directory }}.zip
        retention-days: 5
    
